config/routes.rb
ClientStorage::Application.routes.draw do
  resources :shared_resources

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  resources :groups
end

app/models/shared_resource.rb
class SharedResource < ActiveRecord::Base
  belongs_to :shares, polymorphic: true
end

app/controllers/shared_resources_controller.rb
class SharedResourcesController < ApplicationController
  before_action :set_shared_resource, only: [:show, :edit, :update, :destroy]

  # GET /shared_resources
  # GET /shared_resources.json
  def index
    @shared_resources = SharedResource.all
  end

  # GET /shared_resources/1
  # GET /shared_resources/1.json
  def show
  end

  # GET /shared_resources/new
  def new
    @shared_resource = SharedResource.new
  end

  # GET /shared_resources/1/edit
  def edit
  end

  # POST /shared_resources
  # POST /shared_resources.json
  def create
    @shared_resource = SharedResource.new(shared_resource_params)

    respond_to do |format|
      if @shared_resource.save
        format.html { redirect_to @shared_resource, notice: 'Shared resource was successfully created.' }
        format.json { render action: 'show', status: :created, location: @shared_resource }
      else
        format.html { render action: 'new' }
        format.json { render json: @shared_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shared_resources/1
  # PATCH/PUT /shared_resources/1.json
  def update
    respond_to do |format|
      if @shared_resource.update(shared_resource_params)
        format.html { redirect_to @shared_resource, notice: 'Shared resource was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shared_resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shared_resources/1
  # DELETE /shared_resources/1.json
  def destroy
    @shared_resource.destroy
    respond_to do |format|
      format.html { redirect_to shared_resources_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shared_resource
      @shared_resource = SharedResource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shared_resource_params
      params.require(:shared_resource).permit(:path, :directory, :read, :write)
    end
end

app/helpers/shared_resources_helper.rb
module SharedResourcesHelper
end

app/views/shared_resources/_form.html.haml
= simple_form_for(@shared_resource) do |f|
  = f.error_notification

  .form-inputs
    = f.input :path
    = f.input :directory
    = f.input :read
    = f.input :write

  .form-actions
    = f.button :submit

app/views/shared_resources/edit.html.haml
%h1 Editing shared_resource

= render 'form'

= link_to 'Show', @shared_resource
\|
= link_to 'Back', shared_resources_path

app/views/shared_resources/index.html.haml
%h1 Listing shared_resources

%table
  %tr
    %th Path
    %th Directory
    %th Read
    %th Write
    %th
    %th
    %th

  - @shared_resources.each do |shared_resource|
    %tr
      %td= shared_resource.path
      %td= shared_resource.directory
      %td= shared_resource.read
      %td= shared_resource.write
      %td= link_to 'Show', shared_resource
      %td= link_to 'Edit', edit_shared_resource_path(shared_resource)
      %td= link_to 'Destroy', shared_resource, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Shared resource', new_shared_resource_path

app/views/shared_resources/new.html.haml
%h1 New shared_resource

= render 'form'

= link_to 'Back', shared_resources_path

app/views/shared_resources/show.html.haml
%p#notice= notice

%p
  %b Path:
  = @shared_resource.path
%p
  %b Directory:
  = @shared_resource.directory
%p
  %b Read:
  = @shared_resource.read
%p
  %b Write:
  = @shared_resource.write

= link_to 'Edit', edit_shared_resource_path(@shared_resource)
\|
= link_to 'Back', shared_resources_path